# Generated by Django 4.0.1 on 2022-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
