# Generated by Django 4.0.1 on 2022-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_author_date_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=14),
        ),
    ]
