# Generated by Django 4.0.1 on 2022-01-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='date_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
