# Generated by Django 4.0.1 on 2022-01-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
